### ISSUE TITLE
socket.error: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by praddyinstant** [swateek/Quora-Activity-Report#2]
I getting this error when i try to run the app.py. I have never used Selenium before so not sure what is causing this connection reset or if any settings need to be changed.

Traceback (most recent call last):
  File "app/app.py", line 162, in <module>
    FetchAnswersCSV().run()
  File "app/app.py", line 151, in run
    self.infinite_scroll()
  File "app/app.py", line 74, in infinite_scroll
    self.click_on_more_btn()
  File "app/app.py", line 55, in click_on_more_btn
    question_block = self.driver.find_elements_by_class_name('ui_qtext_more_link')
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 579, in find_elements_by_class_name
    return self.find_elements(by=By.CLASS_NAME, value=name)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 995, in find_elements
    'value': value})['value'] or []
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 496, in _request
    resp = self._conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer

**Comment by swateek** [comment]
Not sure either.

1. Do you have Firefox installed?
2. Have you set your username and password?

**Comment by praddyinstant** [comment]
1. Yes
2. both are set to valid input. Login is successful through the script.
forgot to mention. The firefox launch was successful and also got to the point of my Quora Profile which lists all the answers and then this error occurs.

**Comment by praddyinstant** [comment]
I believe the error could be due to 
` File "app/app.py", line 55, in click_on_more_btn`
I do not have lot of answers on Quora and I might not have this button on the profile page.
